config/routes.rb
Green::Application.routes.draw do
  
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  
  

  

  root :to => 'static_pages#home'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name, presence: true, length: { maximum: 30 }
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  

  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

	private

    	def create_remember_token
      		self.remember_token = SecureRandom.urlsafe_base64
    	end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
  def new

	end

	def create
  
  		user = User.find_by_email(params[:session][:email].downcase)
  
  		if user && user.authenticate(params[:session][:password])
    		# Sign the user in and redirect to the user's show page.
	  		sign_in user
      	redirect_back_or user
    
    	else
      	#flash.now[:error] = 'Invalid email/password combination'
    		# Create an error message and re-render the signin form.
        #notice: 'Notice'
        #flash[:error] = 'Invalid email/password combination' # Not quite right!
    		render 'new'
  		end
	end

	def destroy
    # user = User.find_by_email(params[:session][:email].downcase)
  	 sign_out
     redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end 

  def contact 
  end 

  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  


  #The authorization application code uses a before filter, which 
  # To require users to be signed in, we define a signed_in_user method and 
  # invoke it using before_filter :signed_in_user,arranges for a particular method 
  # to be called before the given actions


  # private defined further down
  before_filter :signed_in_user, only: [:index, :edit, :update, :destroy] # :show
  before_filter :correct_user,   only: [:edit, :update] # :destroy, :show
  before_filter :admin_user,     only: :destroy
   

  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|

      if @user.save
        sign_in @user
        #flash[:success] = "Welcome to the Sample App!"
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

    private

      def signed_in_user
       unless signed_in?
          store_location  # in session helper
          redirect_to signin_url, notice: "Please sign in." unless signed_in?
       end 
      end

      def correct_user
        @user = User.find(params[:id])
        redirect_to(root_path) unless current_user?(@user) # session helper
      end

    
end

app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Green"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
	 
 
  
  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    	@current_user = user
  end

 	def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
    #@current_user     # Useless! Don't use this line.
  end

   def current_user?(user)
    user == current_user
  end
  
  
  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token) 
  end

  def sign_in(user)
      cookies.permanent[:remember_token] = user.remember_token
      self.current_user = user
  end
  
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">My Blog</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "Green", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home", root_path %></li>
              <li><%= link_to "Help", help_path %></li>
              
              <% if signed_in? %>
                
                <li><%= link_to "Users", users_path %></li>
                
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li>
                      <%= link_to "Sign out", signout_path, method: "delete" %>
                    </li>
                  </ul>
                </li>
              
              <% else %>
                <li><%= link_to "Sign in", signin_path %></li>
              <% end %>
            
            </ul>
          </nav>
        </div>
      </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>

</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
	<%= yield %>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>About Us</h1>
	<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to Green</h1>

  <h2>
    This is the home page for Green
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/_form.html.erb
<div class="row">
 <div class="span6 offset3">
  
  
  <%= form_for(@user) do |f| %>
    
    <% if @user.errors.any? %>
      
      <div id="error_explanation">
        
        <h2>This form contains <%= pluralize(@user.errors.count, "error") %>:
        </h2>
        

        <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
        </ul>
    
     </div>

     <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
    
  <%= f.label :email %>
  <%= f.text_field :email %>
     
  <%= f.label :password %>
  <%= f.password_field :password %>
     
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>
      
  <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>

<% end %>

</div>
</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>


<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    
    <% if current_user.admin? && !current_user?(user) %>
      <td><%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
      </td>
    <% end %>

  </tr>
<% end %>

</table>

<br> 
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1> Sign up </h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>